export const state = () => ({
  gameSetupState: 0,
  currentGame: {},
  currentGameStatus: false,
  gameHistory: [],
  loggedInStatus: false,
})

export const getters = {
  getCurrentGameStatus(state) {
    return state.currentGameStatus
  },
  getCurrentGame(state) {
    return state.currentGame
  },
  getGameHistory(state) {
    return state.gameHistory
  },
  getLoggedInStatus(state) {
    return state.loggedInStatus
  },
}

export const mutations = {
  SET_CURRENT_GAME_STATUS_FALSE(state) {
    state.currentGameStatus = false
  },
  SET_CURRENT_GAME_STATUS_TRUE(state) {
    state.currentGameStatus = true
  },
  ADD_BASKET(state, scoreObject) {
    state.currentGame.baskets.push(scoreObject)
  },
  EDIT_BASKET(state, index, scoreObject) {
    state.currentGame.baskets[index] = scoreObject
  },
  ADD_CURRENT_GAME_TO_HISTORY(state) {
    state.gameHistory.push(state.currentGame)
  },
  CLEAR_CURRENT_GAME(state) {
    //  state.currentGame = {
    //    id: null,
    //    date: null,
    //    course: null,
    //    players: [],
    //    baskets: [],
    //  }
    state.currentGame = null
  },
  CREATE_NEW_GAME(state, gameObject) {
    state.currentGame = gameObject
  },
  SET_LOGGED_IN_STATUS(state, boolean) {
    state.loggedInStatus = boolean
  },
}

export const actions = {
  // async restoreCurrentGame() {
  //    // reach out to DB?
  // }

  /* async */
  // createNewGame({ state }, ) {
  //    const gameObject = {
  //       // id: state.gameHistory.length,
  //       course:

  //    }
  // }
  clearGame(context) {
    context.commit('CLEAR_GAME')
  },
  startNewGame(context, { course, players }) {
    /** do some validation */
    const newGame = {
      course,
      date: Date.now(),
      players,
      baskets: [],
    }
    context.commit('CREATE_NEW_GAME', newGame)
    context.commit('SET_CURRENT_GAME_STATUS_TRUE')
  },
  finishCurrentGame(context) {
    context.commit('ADD_CURRENT_GAME_TO_HISTORY')
    context.commit('SET_CURRENT_GAME_STATUS_FALSE')
  },
  addBasket(context, payload) {
    context.commit('ADD_BASKET', payload)
    /**
    * const basket = {
      hole: 1,
    }
    for (let i = 0; i < players.length; i++) {
      basket[players[i]] = 0
    }
    */
  },
  setLoggedInStatus(context, boolean) {
    context.commit('SET_LOGGED_IN_STATUS', boolean)
  },
}

/**
 * Game object:
 * {
 *    id: <Number> (autogenerated)
 *    course_name: <String>
 *    date: <String> (Date)
 *    players: <Array[String]>
 *    baskets: [
 *       {
 *          BasketName: 1 (String to accomodate stuff like '8a')
 *          Scores: [
 *          {Name1: 3}
 *          {Name2: 4}
 *          ]
 *          Par: 3 (default)
 *          Notes?
 *       },
 *       {
 *          Name: 2,
 *          Name1: 4
 *          Name2: 3
 *          Par: 3
 *       },
 *       ...
 *    ]
 * }
 *
 */
